// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmMJj3Flpc5Wo5HLy90HLvI0J3JHzxBrw',
    appId: '1:880387963553:web:ffe00220d0281448768ee0',
    messagingSenderId: '880387963553',
    projectId: 'flutterlogin-97893',
    authDomain: 'flutterlogin-97893-9ffbb.firebaseapp.com',
    storageBucket: 'flutterlogin-97893.appspot.com',
    measurementId: 'G-S019ZQXG7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY3s1rKXP5bzz0FvkFCzj_9xFpA7oSMTM',
    appId: '1:880387963553:android:0e9f6fd346623849768ee0',
    messagingSenderId: '880387963553',
    projectId: 'flutterlogin-97893',
    storageBucket: 'flutterlogin-97893.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIWqpBjSw7gaefW35_Ko0HWIu7wGyzvhA',
    appId: '1:880387963553:ios:1efea4b5bdc3fb37768ee0',
    messagingSenderId: '880387963553',
    projectId: 'flutterlogin-97893',
    storageBucket: 'flutterlogin-97893.appspot.com',
    iosBundleId: 'com.Jun.su.loginPracticeProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIWqpBjSw7gaefW35_Ko0HWIu7wGyzvhA',
    appId: '1:880387963553:ios:2d8b80c8a3aa93cf768ee0',
    messagingSenderId: '880387963553',
    projectId: 'flutterlogin-97893',
    storageBucket: 'flutterlogin-97893.appspot.com',
    iosBundleId: 'com.Jun.su.loginPracticeProject.RunnerTests',
  );
}
